// clang-format off
//
//    BSD 3-Clause License
//    Copyright (c) 2022, Berkay Yigit (berkayylmao) <mail@berkay.link>
//    All rights reserved.
//
//    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
//    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
//    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
//    FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
//    DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
//    SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
//    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
//    OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
//    OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//    You should have received a copy of the BSD 3-Clause License along with
//    this program. If not, see <https://opensource.org/licenses/BSD-3-Clause/>.
//
// clang-format on

#ifndef NFSPLUGINSDK_GAME_MW05_TYPES_ACTIONDATA_H
#define NFSPLUGINSDK_GAME_MW05_TYPES_ACTIONDATA_H
#pragma once

#include <NFSPluginSDK/Game.MW05/Types.h>

namespace NFSPluginSDK::MW05 {
  struct ActionData {
    enum class ActionID : std::uint32_t {
      NULL_ACTION,
      GAMEACTION_STEERLEFT,
      GAMEACTION_STEERRIGHT,
      GAMEACTION_TURNLEFT,
      GAMEACTION_TURNRIGHT,
      GAMEACTION_GAS,
      GAMEACTION_BRAKE,
      GAMEACTION_HANDBRAKE,
      GAMEACTION_GAMEBREAKER,
      GAMEACTION_SHIFTUP,
      GAMEACTION_SHIFTDOWN,
      GAMEACTION_NOS,
      GAMEACTION_RESET,
      GAMEACTION_FORWARD,
      GAMEACTION_BACK,
      GAMEACTION_JUMP,
      GAMEACTION_DEBUGHUMAN1,
      GAMEACTION_DEBUGHUMAN2,
      GAMEACTION_DEBUGHUMAN3,
      GAMEACTION_DEBUGHUMAN4,
      CAMERAACTION_CHANGE,
      CAMERAACTION_DEBUG,
      CAMERAACTION_ENABLE_ICE,
      CAMERAACTION_LOOKBACK,
      CAMERAACTION_PULLBACK,
      FRONTENDACTION_UP,
      FRONTENDACTION_DOWN,
      FRONTENDACTION_LEFT,
      FRONTENDACTION_RIGHT,
      FRONTENDACTION_RUP,
      FRONTENDACTION_RDOWN,
      FRONTENDACTION_RLEFT,
      FRONTENDACTION_RRIGHT,
      FRONTENDACTION_ACCEPT,
      FRONTENDACTION_CANCEL,
      FRONTENDACTION_CANCEL_ALT,
      FRONTENDACTION_START,
      FRONTENDACTION_BUTTON0,
      FRONTENDACTION_BUTTON1,
      FRONTENDACTION_BUTTON2,
      FRONTENDACTION_BUTTON3,
      FRONTENDACTION_BUTTON4,
      FRONTENDACTION_BUTTON5,
      FRONTENDACTION_LTRIGGER,
      FRONTENDACTION_RTRIGGER,
      HUDACTION_PAUSEREQUEST,
      HUDACTION_ENGAGE_EVENT,
      HUDACTION_PAD_LEFT,
      HUDACTION_PAD_DOWN,
      HUDACTION_PAD_RIGHT,
      HUDACTION_SKIPNIS,
      HUDACTION_NEXTSONG,
      VOIPACTION_PUSHTOTALK,
      DEBUGACTION_MOVE_UP,
      DEBUGACTION_MOVE_DOWN,
      DEBUGACTION_MOVE_LEFT,
      DEBUGACTION_MOVE_RIGHT,
      DEBUGACTION_MOVE_FORWARD,
      DEBUGACTION_MOVE_BACK,
      DEBUGACTION_MOVE_D_LEFT,
      DEBUGACTION_MOVE_D_RIGHT,
      DEBUGACTION_MOVE_D_FORWARD,
      DEBUGACTION_MOVE_D_BACK,
      DEBUGACTION_LOOK_UP,
      DEBUGACTION_LOOK_DOWN,
      DEBUGACTION_LOOK_LEFT,
      DEBUGACTION_LOOK_RIGHT,
      DEBUGACTION_LOOK_D_UP,
      DEBUGACTION_LOOK_D_DOWN,
      DEBUGACTION_LOOK_D_LEFT,
      DEBUGACTION_LOOK_D_RIGHT,
      DEBUGACTION_TURBO,
      DEBUGACTION_SUPER_TURBO,
      DEBUGACTION_DROPCAR,
      DEBUGACTION_TOGGLEAI,
      DEBUGACTION_TOGGLESIMSTEP,
      DEBUGACTION_SIMSTEP,
      DEBUGACTION_SCREENSHOT,
      DEBUGACTION_STOPRECORDPATH,
      DEBUGACTION_TOGGLECARCOLOUR,
      DEBUGACTION_TOGGLEDEMOCAMERAS,
      ICEACTION_GRAB_LEFT,
      ICEACTION_GRAB_RIGHT,
      ICEACTION_LEFT,
      ICEACTION_RIGHT,
      ICEACTION_FAST_LEFT,
      ICEACTION_FAST_RIGHT,
      ICEACTION_UP,
      ICEACTION_DOWN,
      ICEACTION_HELP,
      ICEACTION_UNDO,
      ICEACTION_PLAY,
      ICEACTION_HIDE,
      ICEACTION_SCREENSHOT,
      ICEACTION_SCREENSHOT_STREAM,
      ICEACTION_INSERT,
      ICEACTION_CUT,
      ICEACTION_COPY,
      ICEACTION_PASTE,
      ICEACTION_SELECT,
      ICEACTION_CANCEL,
      ICEACTION_ALT_1,
      ICEACTION_CLIP_IN,
      ICEACTION_CLIP_OUT,
      ICEACTION_SIMSPEED_INC,
      ICEACTION_SIMSPEED_DEC,
      ICEACTION_DUTCH_LEFT,
      ICEACTION_DUTCH_RIGHT,
      ICEACTION_ZOOM_IN,
      ICEACTION_ZOOM_OUT,
      ICEACTION_LETTERBOX_IN,
      ICEACTION_LETTERBOX_OUT,
      ICEACTION_BUBBLE_IN,
      ICEACTION_BUBBLE_OUT,
      ICEACTION_BUBBLE_UP,
      ICEACTION_BUBBLE_DOWN,
      ICEACTION_BUBBLE_TILT_UP,
      ICEACTION_BUBBLE_TILT_DOWN,
      ICEACTION_BUBBLE_SPIN_LEFT,
      ICEACTION_BUBBLE_SPIN_RIGHT,
      ICEACTION_BUBBLE_LEFT,
      ICEACTION_BUBBLE_RIGHT,
      ICEACTION_BUBBLE_BACK,
      ICEACTION_BUBBLE_FORTH,
      ICEACTION_SHAKE_MAG_DEC,
      ICEACTION_SHAKE_MAG_INC,
      ICEACTION_SHAKE_FRQ_DEC,
      ICEACTION_SHAKE_FRQ_INC,
      ICEACTION_SHUTTLE_LEFT,
      ICEACTION_SHUTTLE_RIGHT,
      ICEACTION_SHUTTLE_UP,
      ICEACTION_SHUTTLE_DOWN,
      ICEACTION_SHUTTLE_SPEED_DEC,
      ICEACTION_SHUTTLE_SPEED_INC,
      ACTION_EXITAPPLICATION,
      ACTION_PLUGGED,
      ACTION_UNPLUGGED,
      ACTION_FLUSH
    };

    ActionID     mId;
    std::int32_t mSlot;
    float        mData;
  };
}  // namespace NFSPluginSDK::MW05

#endif  // NFSPLUGINSDK_GAME_MW05_TYPES_ACTIONDATA_H
